//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&CollectorConfig{}, func(obj interface{}) { SetObjectDefaults_CollectorConfig(obj.(*CollectorConfig)) })
	return nil
}

func SetObjectDefaults_CollectorConfig(in *CollectorConfig) {
	if in.Spec.Exporters.OTLPGRPCExporter.Enabled == nil {
		var ptrVar1 bool = false
		in.Spec.Exporters.OTLPGRPCExporter.Enabled = &ptrVar1
	}
	if in.Spec.Exporters.OTLPGRPCExporter.TLS != nil {
		if in.Spec.Exporters.OTLPGRPCExporter.TLS.InsecureSkipVerify == nil {
			var ptrVar1 bool = false
			in.Spec.Exporters.OTLPGRPCExporter.TLS.InsecureSkipVerify = &ptrVar1
		}
	}
	if in.Spec.Exporters.OTLPGRPCExporter.Timeout == 0 {
		in.Spec.Exporters.OTLPGRPCExporter.Timeout = time.Duration(DefaultGRPCExporterClientTimeout)
	}
	if in.Spec.Exporters.OTLPGRPCExporter.ReadBufferSize == 0 {
		in.Spec.Exporters.OTLPGRPCExporter.ReadBufferSize = int(DefaultGRPCExporterClientReadBufferSize)
	}
	if in.Spec.Exporters.OTLPGRPCExporter.WriteBufferSize == 0 {
		in.Spec.Exporters.OTLPGRPCExporter.WriteBufferSize = int(DefaultGRPCExporterClientWriteBufferSize)
	}
	if in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.Enabled == nil {
		var ptrVar1 bool = true
		in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.Enabled = &ptrVar1
	}
	if in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.InitialInterval == 0 {
		in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
	}
	if in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.MaxInterval == 0 {
		in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
	}
	if in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.MaxElapsedTime == 0 {
		in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
	}
	if in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.Multiplier == 0 {
		in.Spec.Exporters.OTLPGRPCExporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
	}
	if in.Spec.Exporters.OTLPGRPCExporter.Compression == "" {
		in.Spec.Exporters.OTLPGRPCExporter.Compression = Compression(CompressionGzip)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.Enabled == nil {
		var ptrVar1 bool = false
		in.Spec.Exporters.OTLPHTTPExporter.Enabled = &ptrVar1
	}
	if in.Spec.Exporters.OTLPHTTPExporter.TLS != nil {
		if in.Spec.Exporters.OTLPHTTPExporter.TLS.InsecureSkipVerify == nil {
			var ptrVar1 bool = false
			in.Spec.Exporters.OTLPHTTPExporter.TLS.InsecureSkipVerify = &ptrVar1
		}
	}
	if in.Spec.Exporters.OTLPHTTPExporter.Timeout == 0 {
		in.Spec.Exporters.OTLPHTTPExporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.ReadBufferSize == 0 {
		in.Spec.Exporters.OTLPHTTPExporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.WriteBufferSize == 0 {
		in.Spec.Exporters.OTLPHTTPExporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.Encoding == "" {
		in.Spec.Exporters.OTLPHTTPExporter.Encoding = MessageEncoding(MessageEncodingProto)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.Enabled == nil {
		var ptrVar1 bool = true
		in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.Enabled = &ptrVar1
	}
	if in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.InitialInterval == 0 {
		in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.MaxInterval == 0 {
		in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.MaxElapsedTime == 0 {
		in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.Multiplier == 0 {
		in.Spec.Exporters.OTLPHTTPExporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
	}
	if in.Spec.Exporters.OTLPHTTPExporter.Compression == "" {
		in.Spec.Exporters.OTLPHTTPExporter.Compression = Compression(CompressionGzip)
	}
	if in.Spec.Exporters.DebugExporter.Enabled == nil {
		var ptrVar1 bool = false
		in.Spec.Exporters.DebugExporter.Enabled = &ptrVar1
	}
	if in.Spec.Exporters.DebugExporter.Verbosity == "" {
		in.Spec.Exporters.DebugExporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
	}
	if in.Spec.Logs.Level == "" {
		in.Spec.Logs.Level = LogLevel(LogLevelInfo)
	}
	if in.Spec.Logs.Encoding == "" {
		in.Spec.Logs.Encoding = LogEncoding(LogEncodingConsole)
	}
	if in.Spec.Metrics.Level == "" {
		in.Spec.Metrics.Level = MetricsVerbosityLevel(MetricsVerbosityLevelNormal)
	}
}
