//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-otelcol/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CollectorConfig)(nil), (*config.CollectorConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CollectorConfig_To_config_CollectorConfig(a.(*CollectorConfig), b.(*config.CollectorConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CollectorConfig)(nil), (*CollectorConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CollectorConfig_To_v1alpha1_CollectorConfig(a.(*config.CollectorConfig), b.(*CollectorConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CollectorConfigSpec)(nil), (*config.CollectorConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(a.(*CollectorConfigSpec), b.(*config.CollectorConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CollectorConfigSpec)(nil), (*CollectorConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(a.(*config.CollectorConfigSpec), b.(*CollectorConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CollectorExportersConfig)(nil), (*config.CollectorExportersConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CollectorExportersConfig_To_config_CollectorExportersConfig(a.(*CollectorExportersConfig), b.(*config.CollectorExportersConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CollectorExportersConfig)(nil), (*CollectorExportersConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CollectorExportersConfig_To_v1alpha1_CollectorExportersConfig(a.(*config.CollectorExportersConfig), b.(*CollectorExportersConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CollectorLogsConfig)(nil), (*config.CollectorLogsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(a.(*CollectorLogsConfig), b.(*config.CollectorLogsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CollectorLogsConfig)(nil), (*CollectorLogsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(a.(*config.CollectorLogsConfig), b.(*CollectorLogsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DebugExporterConfig)(nil), (*config.DebugExporterConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DebugExporterConfig_To_config_DebugExporterConfig(a.(*DebugExporterConfig), b.(*config.DebugExporterConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DebugExporterConfig)(nil), (*DebugExporterConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DebugExporterConfig_To_v1alpha1_DebugExporterConfig(a.(*config.DebugExporterConfig), b.(*DebugExporterConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OTLPHTTPExporterConfig)(nil), (*config.OTLPHTTPExporterConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OTLPHTTPExporterConfig_To_config_OTLPHTTPExporterConfig(a.(*OTLPHTTPExporterConfig), b.(*config.OTLPHTTPExporterConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.OTLPHTTPExporterConfig)(nil), (*OTLPHTTPExporterConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_OTLPHTTPExporterConfig_To_v1alpha1_OTLPHTTPExporterConfig(a.(*config.OTLPHTTPExporterConfig), b.(*OTLPHTTPExporterConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceReference)(nil), (*config.ResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceReference_To_config_ResourceReference(a.(*ResourceReference), b.(*config.ResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ResourceReference)(nil), (*ResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ResourceReference_To_v1alpha1_ResourceReference(a.(*config.ResourceReference), b.(*ResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceReferenceDetails)(nil), (*config.ResourceReferenceDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(a.(*ResourceReferenceDetails), b.(*config.ResourceReferenceDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ResourceReferenceDetails)(nil), (*ResourceReferenceDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(a.(*config.ResourceReferenceDetails), b.(*ResourceReferenceDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RetryOnFailureConfig)(nil), (*config.RetryOnFailureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(a.(*RetryOnFailureConfig), b.(*config.RetryOnFailureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RetryOnFailureConfig)(nil), (*RetryOnFailureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(a.(*config.RetryOnFailureConfig), b.(*RetryOnFailureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLSConfig)(nil), (*config.TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TLSConfig_To_config_TLSConfig(a.(*TLSConfig), b.(*config.TLSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TLSConfig)(nil), (*TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TLSConfig_To_v1alpha1_TLSConfig(a.(*config.TLSConfig), b.(*TLSConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CollectorConfig_To_config_CollectorConfig(in *CollectorConfig, out *config.CollectorConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CollectorConfig_To_config_CollectorConfig is an autogenerated conversion function.
func Convert_v1alpha1_CollectorConfig_To_config_CollectorConfig(in *CollectorConfig, out *config.CollectorConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CollectorConfig_To_config_CollectorConfig(in, out, s)
}

func autoConvert_config_CollectorConfig_To_v1alpha1_CollectorConfig(in *config.CollectorConfig, out *CollectorConfig, s conversion.Scope) error {
	if err := Convert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_CollectorConfig_To_v1alpha1_CollectorConfig is an autogenerated conversion function.
func Convert_config_CollectorConfig_To_v1alpha1_CollectorConfig(in *config.CollectorConfig, out *CollectorConfig, s conversion.Scope) error {
	return autoConvert_config_CollectorConfig_To_v1alpha1_CollectorConfig(in, out, s)
}

func autoConvert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(in *CollectorConfigSpec, out *config.CollectorConfigSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_CollectorExportersConfig_To_config_CollectorExportersConfig(&in.Exporters, &out.Exporters, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(&in.Logs, &out.Logs, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(in *CollectorConfigSpec, out *config.CollectorConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(in, out, s)
}

func autoConvert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(in *config.CollectorConfigSpec, out *CollectorConfigSpec, s conversion.Scope) error {
	if err := Convert_config_CollectorExportersConfig_To_v1alpha1_CollectorExportersConfig(&in.Exporters, &out.Exporters, s); err != nil {
		return err
	}
	if err := Convert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(&in.Logs, &out.Logs, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec is an autogenerated conversion function.
func Convert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(in *config.CollectorConfigSpec, out *CollectorConfigSpec, s conversion.Scope) error {
	return autoConvert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_CollectorExportersConfig_To_config_CollectorExportersConfig(in *CollectorExportersConfig, out *config.CollectorExportersConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_OTLPHTTPExporterConfig_To_config_OTLPHTTPExporterConfig(&in.OTLPHTTPExporter, &out.OTLPHTTPExporter, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DebugExporterConfig_To_config_DebugExporterConfig(&in.DebugExporter, &out.DebugExporter, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CollectorExportersConfig_To_config_CollectorExportersConfig is an autogenerated conversion function.
func Convert_v1alpha1_CollectorExportersConfig_To_config_CollectorExportersConfig(in *CollectorExportersConfig, out *config.CollectorExportersConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CollectorExportersConfig_To_config_CollectorExportersConfig(in, out, s)
}

func autoConvert_config_CollectorExportersConfig_To_v1alpha1_CollectorExportersConfig(in *config.CollectorExportersConfig, out *CollectorExportersConfig, s conversion.Scope) error {
	if err := Convert_config_OTLPHTTPExporterConfig_To_v1alpha1_OTLPHTTPExporterConfig(&in.OTLPHTTPExporter, &out.OTLPHTTPExporter, s); err != nil {
		return err
	}
	if err := Convert_config_DebugExporterConfig_To_v1alpha1_DebugExporterConfig(&in.DebugExporter, &out.DebugExporter, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_CollectorExportersConfig_To_v1alpha1_CollectorExportersConfig is an autogenerated conversion function.
func Convert_config_CollectorExportersConfig_To_v1alpha1_CollectorExportersConfig(in *config.CollectorExportersConfig, out *CollectorExportersConfig, s conversion.Scope) error {
	return autoConvert_config_CollectorExportersConfig_To_v1alpha1_CollectorExportersConfig(in, out, s)
}

func autoConvert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(in *CollectorLogsConfig, out *config.CollectorLogsConfig, s conversion.Scope) error {
	out.Level = config.LogLevel(in.Level)
	out.Encoding = config.LogEncoding(in.Encoding)
	return nil
}

// Convert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig is an autogenerated conversion function.
func Convert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(in *CollectorLogsConfig, out *config.CollectorLogsConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(in, out, s)
}

func autoConvert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(in *config.CollectorLogsConfig, out *CollectorLogsConfig, s conversion.Scope) error {
	out.Level = LogLevel(in.Level)
	out.Encoding = LogEncoding(in.Encoding)
	return nil
}

// Convert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig is an autogenerated conversion function.
func Convert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(in *config.CollectorLogsConfig, out *CollectorLogsConfig, s conversion.Scope) error {
	return autoConvert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(in, out, s)
}

func autoConvert_v1alpha1_DebugExporterConfig_To_config_DebugExporterConfig(in *DebugExporterConfig, out *config.DebugExporterConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Verbosity = config.DebugExporterVerbosity(in.Verbosity)
	return nil
}

// Convert_v1alpha1_DebugExporterConfig_To_config_DebugExporterConfig is an autogenerated conversion function.
func Convert_v1alpha1_DebugExporterConfig_To_config_DebugExporterConfig(in *DebugExporterConfig, out *config.DebugExporterConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DebugExporterConfig_To_config_DebugExporterConfig(in, out, s)
}

func autoConvert_config_DebugExporterConfig_To_v1alpha1_DebugExporterConfig(in *config.DebugExporterConfig, out *DebugExporterConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Verbosity = DebugExporterVerbosity(in.Verbosity)
	return nil
}

// Convert_config_DebugExporterConfig_To_v1alpha1_DebugExporterConfig is an autogenerated conversion function.
func Convert_config_DebugExporterConfig_To_v1alpha1_DebugExporterConfig(in *config.DebugExporterConfig, out *DebugExporterConfig, s conversion.Scope) error {
	return autoConvert_config_DebugExporterConfig_To_v1alpha1_DebugExporterConfig(in, out, s)
}

func autoConvert_v1alpha1_OTLPHTTPExporterConfig_To_config_OTLPHTTPExporterConfig(in *OTLPHTTPExporterConfig, out *config.OTLPHTTPExporterConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Endpoint = in.Endpoint
	out.TracesEndpoint = in.TracesEndpoint
	out.MetricsEndpoint = in.MetricsEndpoint
	out.LogsEndpoint = in.LogsEndpoint
	out.ProfilesEndpoint = in.ProfilesEndpoint
	out.TLS = (*config.TLSConfig)(unsafe.Pointer(in.TLS))
	out.Token = (*config.ResourceReference)(unsafe.Pointer(in.Token))
	out.Timeout = time.Duration(in.Timeout)
	out.ReadBufferSize = in.ReadBufferSize
	out.WriteBufferSize = in.WriteBufferSize
	out.Encoding = config.MessageEncoding(in.Encoding)
	if err := Convert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(&in.RetryOnFailure, &out.RetryOnFailure, s); err != nil {
		return err
	}
	out.Compression = config.Compression(in.Compression)
	return nil
}

// Convert_v1alpha1_OTLPHTTPExporterConfig_To_config_OTLPHTTPExporterConfig is an autogenerated conversion function.
func Convert_v1alpha1_OTLPHTTPExporterConfig_To_config_OTLPHTTPExporterConfig(in *OTLPHTTPExporterConfig, out *config.OTLPHTTPExporterConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_OTLPHTTPExporterConfig_To_config_OTLPHTTPExporterConfig(in, out, s)
}

func autoConvert_config_OTLPHTTPExporterConfig_To_v1alpha1_OTLPHTTPExporterConfig(in *config.OTLPHTTPExporterConfig, out *OTLPHTTPExporterConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Endpoint = in.Endpoint
	out.TracesEndpoint = in.TracesEndpoint
	out.MetricsEndpoint = in.MetricsEndpoint
	out.LogsEndpoint = in.LogsEndpoint
	out.ProfilesEndpoint = in.ProfilesEndpoint
	out.TLS = (*TLSConfig)(unsafe.Pointer(in.TLS))
	out.Token = (*ResourceReference)(unsafe.Pointer(in.Token))
	out.Timeout = time.Duration(in.Timeout)
	out.ReadBufferSize = in.ReadBufferSize
	out.WriteBufferSize = in.WriteBufferSize
	out.Encoding = MessageEncoding(in.Encoding)
	if err := Convert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(&in.RetryOnFailure, &out.RetryOnFailure, s); err != nil {
		return err
	}
	out.Compression = Compression(in.Compression)
	return nil
}

// Convert_config_OTLPHTTPExporterConfig_To_v1alpha1_OTLPHTTPExporterConfig is an autogenerated conversion function.
func Convert_config_OTLPHTTPExporterConfig_To_v1alpha1_OTLPHTTPExporterConfig(in *config.OTLPHTTPExporterConfig, out *OTLPHTTPExporterConfig, s conversion.Scope) error {
	return autoConvert_config_OTLPHTTPExporterConfig_To_v1alpha1_OTLPHTTPExporterConfig(in, out, s)
}

func autoConvert_v1alpha1_ResourceReference_To_config_ResourceReference(in *ResourceReference, out *config.ResourceReference, s conversion.Scope) error {
	if err := Convert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(&in.ResourceRef, &out.ResourceRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ResourceReference_To_config_ResourceReference is an autogenerated conversion function.
func Convert_v1alpha1_ResourceReference_To_config_ResourceReference(in *ResourceReference, out *config.ResourceReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceReference_To_config_ResourceReference(in, out, s)
}

func autoConvert_config_ResourceReference_To_v1alpha1_ResourceReference(in *config.ResourceReference, out *ResourceReference, s conversion.Scope) error {
	if err := Convert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(&in.ResourceRef, &out.ResourceRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ResourceReference_To_v1alpha1_ResourceReference is an autogenerated conversion function.
func Convert_config_ResourceReference_To_v1alpha1_ResourceReference(in *config.ResourceReference, out *ResourceReference, s conversion.Scope) error {
	return autoConvert_config_ResourceReference_To_v1alpha1_ResourceReference(in, out, s)
}

func autoConvert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(in *ResourceReferenceDetails, out *config.ResourceReferenceDetails, s conversion.Scope) error {
	out.Name = in.Name
	out.DataKey = in.DataKey
	return nil
}

// Convert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails is an autogenerated conversion function.
func Convert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(in *ResourceReferenceDetails, out *config.ResourceReferenceDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(in, out, s)
}

func autoConvert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(in *config.ResourceReferenceDetails, out *ResourceReferenceDetails, s conversion.Scope) error {
	out.Name = in.Name
	out.DataKey = in.DataKey
	return nil
}

// Convert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails is an autogenerated conversion function.
func Convert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(in *config.ResourceReferenceDetails, out *ResourceReferenceDetails, s conversion.Scope) error {
	return autoConvert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(in, out, s)
}

func autoConvert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(in *RetryOnFailureConfig, out *config.RetryOnFailureConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.InitialInterval = time.Duration(in.InitialInterval)
	out.MaxInterval = time.Duration(in.MaxInterval)
	out.MaxElapsedTime = time.Duration(in.MaxElapsedTime)
	out.Multiplier = in.Multiplier
	return nil
}

// Convert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig is an autogenerated conversion function.
func Convert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(in *RetryOnFailureConfig, out *config.RetryOnFailureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(in, out, s)
}

func autoConvert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(in *config.RetryOnFailureConfig, out *RetryOnFailureConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.InitialInterval = time.Duration(in.InitialInterval)
	out.MaxInterval = time.Duration(in.MaxInterval)
	out.MaxElapsedTime = time.Duration(in.MaxElapsedTime)
	out.Multiplier = in.Multiplier
	return nil
}

// Convert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig is an autogenerated conversion function.
func Convert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(in *config.RetryOnFailureConfig, out *RetryOnFailureConfig, s conversion.Scope) error {
	return autoConvert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(in, out, s)
}

func autoConvert_v1alpha1_TLSConfig_To_config_TLSConfig(in *TLSConfig, out *config.TLSConfig, s conversion.Scope) error {
	out.InsecureSkipVerify = (*bool)(unsafe.Pointer(in.InsecureSkipVerify))
	out.CA = (*config.ResourceReference)(unsafe.Pointer(in.CA))
	out.Cert = (*config.ResourceReference)(unsafe.Pointer(in.Cert))
	out.Key = (*config.ResourceReference)(unsafe.Pointer(in.Key))
	return nil
}

// Convert_v1alpha1_TLSConfig_To_config_TLSConfig is an autogenerated conversion function.
func Convert_v1alpha1_TLSConfig_To_config_TLSConfig(in *TLSConfig, out *config.TLSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_TLSConfig_To_config_TLSConfig(in, out, s)
}

func autoConvert_config_TLSConfig_To_v1alpha1_TLSConfig(in *config.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	out.InsecureSkipVerify = (*bool)(unsafe.Pointer(in.InsecureSkipVerify))
	out.CA = (*ResourceReference)(unsafe.Pointer(in.CA))
	out.Cert = (*ResourceReference)(unsafe.Pointer(in.Cert))
	out.Key = (*ResourceReference)(unsafe.Pointer(in.Key))
	return nil
}

// Convert_config_TLSConfig_To_v1alpha1_TLSConfig is an autogenerated conversion function.
func Convert_config_TLSConfig_To_v1alpha1_TLSConfig(in *config.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	return autoConvert_config_TLSConfig_To_v1alpha1_TLSConfig(in, out, s)
}
