//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	config "github.com/gardener/gardener-extension-otelcol/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ExampleConfig)(nil), (*config.ExampleConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExampleConfig_To_config_ExampleConfig(a.(*ExampleConfig), b.(*config.ExampleConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ExampleConfig)(nil), (*ExampleConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ExampleConfig_To_v1alpha1_ExampleConfig(a.(*config.ExampleConfig), b.(*ExampleConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExampleConfigSpec)(nil), (*config.ExampleConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExampleConfigSpec_To_config_ExampleConfigSpec(a.(*ExampleConfigSpec), b.(*config.ExampleConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ExampleConfigSpec)(nil), (*ExampleConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ExampleConfigSpec_To_v1alpha1_ExampleConfigSpec(a.(*config.ExampleConfigSpec), b.(*ExampleConfigSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ExampleConfig_To_config_ExampleConfig(in *ExampleConfig, out *config.ExampleConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_ExampleConfigSpec_To_config_ExampleConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ExampleConfig_To_config_ExampleConfig is an autogenerated conversion function.
func Convert_v1alpha1_ExampleConfig_To_config_ExampleConfig(in *ExampleConfig, out *config.ExampleConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExampleConfig_To_config_ExampleConfig(in, out, s)
}

func autoConvert_config_ExampleConfig_To_v1alpha1_ExampleConfig(in *config.ExampleConfig, out *ExampleConfig, s conversion.Scope) error {
	if err := Convert_config_ExampleConfigSpec_To_v1alpha1_ExampleConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ExampleConfig_To_v1alpha1_ExampleConfig is an autogenerated conversion function.
func Convert_config_ExampleConfig_To_v1alpha1_ExampleConfig(in *config.ExampleConfig, out *ExampleConfig, s conversion.Scope) error {
	return autoConvert_config_ExampleConfig_To_v1alpha1_ExampleConfig(in, out, s)
}

func autoConvert_v1alpha1_ExampleConfigSpec_To_config_ExampleConfigSpec(in *ExampleConfigSpec, out *config.ExampleConfigSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_v1alpha1_ExampleConfigSpec_To_config_ExampleConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_ExampleConfigSpec_To_config_ExampleConfigSpec(in *ExampleConfigSpec, out *config.ExampleConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExampleConfigSpec_To_config_ExampleConfigSpec(in, out, s)
}

func autoConvert_config_ExampleConfigSpec_To_v1alpha1_ExampleConfigSpec(in *config.ExampleConfigSpec, out *ExampleConfigSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_config_ExampleConfigSpec_To_v1alpha1_ExampleConfigSpec is an autogenerated conversion function.
func Convert_config_ExampleConfigSpec_To_v1alpha1_ExampleConfigSpec(in *config.ExampleConfigSpec, out *ExampleConfigSpec, s conversion.Scope) error {
	return autoConvert_config_ExampleConfigSpec_To_v1alpha1_ExampleConfigSpec(in, out, s)
}
