//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorConfig) DeepCopyInto(out *CollectorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorConfig.
func (in *CollectorConfig) DeepCopy() *CollectorConfig {
	if in == nil {
		return nil
	}
	out := new(CollectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorConfigSpec) DeepCopyInto(out *CollectorConfigSpec) {
	*out = *in
	in.Exporters.DeepCopyInto(&out.Exporters)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorConfigSpec.
func (in *CollectorConfigSpec) DeepCopy() *CollectorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorExportersConfig) DeepCopyInto(out *CollectorExportersConfig) {
	*out = *in
	in.OTLPHTTPExporter.DeepCopyInto(&out.OTLPHTTPExporter)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorExportersConfig.
func (in *CollectorExportersConfig) DeepCopy() *CollectorExportersConfig {
	if in == nil {
		return nil
	}
	out := new(CollectorExportersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTLPHTTPExporterConfig) DeepCopyInto(out *OTLPHTTPExporterConfig) {
	*out = *in
	in.TLS.DeepCopyInto(&out.TLS)
	in.RetryOnFailure.DeepCopyInto(&out.RetryOnFailure)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTLPHTTPExporterConfig.
func (in *OTLPHTTPExporterConfig) DeepCopy() *OTLPHTTPExporterConfig {
	if in == nil {
		return nil
	}
	out := new(OTLPHTTPExporterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryOnFailureConfig) DeepCopyInto(out *RetryOnFailureConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryOnFailureConfig.
func (in *RetryOnFailureConfig) DeepCopy() *RetryOnFailureConfig {
	if in == nil {
		return nil
	}
	out := new(RetryOnFailureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.CurvePreferences != nil {
		in, out := &in.CurvePreferences, &out.CurvePreferences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeSystemCACertsPool != nil {
		in, out := &in.IncludeSystemCACertsPool, &out.IncludeSystemCACertsPool
		*out = new(bool)
		**out = **in
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
	if in.CipherSuites != nil {
		in, out := &in.CipherSuites, &out.CipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
