//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleConfig) DeepCopyInto(out *ExampleConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleConfig.
func (in *ExampleConfig) DeepCopy() *ExampleConfig {
	if in == nil {
		return nil
	}
	out := new(ExampleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExampleConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleConfigSpec) DeepCopyInto(out *ExampleConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleConfigSpec.
func (in *ExampleConfigSpec) DeepCopy() *ExampleConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ExampleConfigSpec)
	in.DeepCopyInto(out)
	return out
}
