//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorConfig) DeepCopyInto(out *CollectorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorConfig.
func (in *CollectorConfig) DeepCopy() *CollectorConfig {
	if in == nil {
		return nil
	}
	out := new(CollectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorConfigSpec) DeepCopyInto(out *CollectorConfigSpec) {
	*out = *in
	in.Exporters.DeepCopyInto(&out.Exporters)
	out.Logs = in.Logs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorConfigSpec.
func (in *CollectorConfigSpec) DeepCopy() *CollectorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorExportersConfig) DeepCopyInto(out *CollectorExportersConfig) {
	*out = *in
	in.OTLPHTTPExporter.DeepCopyInto(&out.OTLPHTTPExporter)
	in.DebugExporter.DeepCopyInto(&out.DebugExporter)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorExportersConfig.
func (in *CollectorExportersConfig) DeepCopy() *CollectorExportersConfig {
	if in == nil {
		return nil
	}
	out := new(CollectorExportersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorLogsConfig) DeepCopyInto(out *CollectorLogsConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorLogsConfig.
func (in *CollectorLogsConfig) DeepCopy() *CollectorLogsConfig {
	if in == nil {
		return nil
	}
	out := new(CollectorLogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugExporterConfig) DeepCopyInto(out *DebugExporterConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugExporterConfig.
func (in *DebugExporterConfig) DeepCopy() *DebugExporterConfig {
	if in == nil {
		return nil
	}
	out := new(DebugExporterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTLPHTTPExporterConfig) DeepCopyInto(out *OTLPHTTPExporterConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(ResourceReference)
		**out = **in
	}
	in.RetryOnFailure.DeepCopyInto(&out.RetryOnFailure)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTLPHTTPExporterConfig.
func (in *OTLPHTTPExporterConfig) DeepCopy() *OTLPHTTPExporterConfig {
	if in == nil {
		return nil
	}
	out := new(OTLPHTTPExporterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
	out.ResourceRef = in.ResourceRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReferenceDetails) DeepCopyInto(out *ResourceReferenceDetails) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReferenceDetails.
func (in *ResourceReferenceDetails) DeepCopy() *ResourceReferenceDetails {
	if in == nil {
		return nil
	}
	out := new(ResourceReferenceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryOnFailureConfig) DeepCopyInto(out *RetryOnFailureConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryOnFailureConfig.
func (in *RetryOnFailureConfig) DeepCopy() *RetryOnFailureConfig {
	if in == nil {
		return nil
	}
	out := new(RetryOnFailureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(ResourceReference)
		**out = **in
	}
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(ResourceReference)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(ResourceReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
