# Default chart values.

# Number of replicas.
replicaCount: 2
# Gardener extension settings.
extension:
  # Name of the Gardener extension.
  #
  # This name will be used when registering the extension with Gardener.
  #
  # Also, it will be used as the name for the Deployment, Service and
  # ServiceAccount resources.
  name: gardener-extension-otelcol
  # Logging settings.
  logging:
    # Logging level. Valid values are `info', `debug' and `error'.
    level: info
    # Logging format. Valid values are `json' and `text'.
    format: json
  # Controller manager settings
  manager:
    # Set to true in order to ignore operation annotation
    ignore_operation_annotation: false
    # Max concurrent reconciles
    max_concurrent_reconciles: 5
    # Number of Queries Per Second for client connections. Set to -1.0 in order
    # to disable client-side rate limiting and rely on API priority and
    # fairness.
    qps: -1.0
    # Extra queries to accumulate when a client is exceeding its rate.
    burst: 0
    # Requeue interval
    resync_interval: 30s
  # Metrics settings
  metrics:
    # Set to false in order to disable scraping from Prometheus.
    enable_scraping: true
    # Metrics server will bind to this address. Set this value to 0 in order to
    # disable metrics server.
    bind_address: ":8080"
  # Health settings
  health:
    bind_address: ":8081"
  # pprof settings. Set this to 0 in order to disable pprof.
  pprof:
    bind_address: ":9090"
  # Heartbeat settings
  heartbeat:
    renew_interval: 30s
  # Leader election settings
  leader_election:
    enabled: true
    election_id: gardener-extension-otelcol-leader-election
  # Memory Limiter Processor configuration for the OTel collector
  memory_limiter:
    # Time between measurements of the memory usage
    check_interval: 1s
    # Max amount of memory in MiB allocated to the process. The `limit_mib'
    # setting takes precedence over `limit_percentage'.
    limit_mib: 2000
    # # Max amount of memory allocated to the process in percentage of total
    # # memory
    # limit_percentage: 75
    # # Max amount of spike between measurements in MiB. The `spike_limit_mib'
    # # setting takes precedence over `spike_limit_percentage'.
    # spike_limit_mib: 500
    # # Max amount of spike between measurements in percentage of total memory
    # spike_limit_percentage: 10
  # Batch Processor configuration for the OTel collector
  batch_processor:
    # Time after which a batch is sent regardless of its size.
    timeout: 5s
    # Send batch when it reaches this size of items.
    batch_size: 2000
    # Max size of a batch. When set to a non-zero value, it must be greater than
    # `batch_size' setting.
    batch_max_size: 4000
# Extra values provided by gardenlet during extension deployment.
#
# See the links below for more details.
#
# https://gardener.cloud/docs/gardener/extensions/registration/#helm-values
# https://github.com/gardener/gardener/blob/d5071c800378616eb6bb2c7662b4b28f4cfe7406/pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go#L236-L263
gardener:
  version: "unknown"
  gardenlet:
    featureGates: {}
# ServiceAccount settings.
#
# The name of the service account is derived from the .Values.extension.name
# value.
#
# See the link below for more details:
#
# https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automount API credentials, if set to true.
  automount: false
  # Additional annotations to add to the service account
  annotations: {}
# Extension image settings.
#
# https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: registry.local.gardener.cloud:5001/extensions/gardener-extension-otelcol
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.0-dev"
# Image pull secrets settings.
#
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# Additional annotations to attach to pods.
#
# Check the following link for more details about annotations.
#
# https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# Additional labels to attach to pods.
#
# Check the following link for more details about labels.
#
# https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels:
  networking.gardener.cloud/to-runtime-apiserver: allowed
  networking.gardener.cloud/to-dns: allowed
# Pod and container security context settings.
#
# For more details about security context check the following documentation.
#
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext: {}
# runAsUser: 1000
# runAsGroup: 2000
# fsGroup: 3000

# Security Context for pod containers.
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
# Service settings.
#
# Check the following link for more details.
#
# https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # Specifies whether a service should be created
  create: true
  # Service type.
  # See: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # Service port.
  # See: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80
# Resources limits and requests
#
# Check the following link for more details.
#
# https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources:
  requests:
    cpu: 50m
    memory: 64Mi
# Horizontal Pod Autoscaling (HPA) settings.
#
# Check the following documentation for more details.
#
# https://kubernetes.io/docs/concepts/workloads/autoscaling/
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
# Vertical Pod Autoscaler (VPA) settings.
#
# Check the following documentation for more details.
#
# https://kubernetes.io/docs/concepts/workloads/autoscaling/
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      memory: 32Mi
    controlledValues: RequestsOnly
  updatePolicy:
    updateMode: Recreate
# Additional volumes for the Deployment resource.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts for the Deployment resource.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}
tolerations: []
affinity: {}
# Fluent Bit Operator managed resources configuration
fluentbit:
  # Enable or disable Fluent Bit deployment
  enabled: false
  # Name of the FluentBit resource
  name: fluent-bit-extension-otelcol
  # Fluent Bit image
  image:
    name: europe-docker.pkg.dev/gardener-project/releases/3rd/fluent-operator/fluent-bit:v4.2.3
    pullPolicy: IfNotPresent
  # Fluent Bit Plugins image
  # europe-docker.pkg.dev/gardener-project/releases/gardener/fluent-bit-plugin:v1.3.0
  pluginImage:
    name: europe-docker.pkg.dev/gardener-project/snapshots/gardener/fluent-bit-plugin:v1.3.0-dev-1650edbd
    pullPolicy: IfNotPresent
  labels:
  annotations:
  # Fluent bit pod probes configuration
  #
  # Check the following link for more details.
  #
  # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  readinessProbe:
    httpGet:
      path: /api/v2/metrics/prometheus
      port: 2020
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /healthz
      port: 2021
    initialDelaySeconds: 120
    periodSeconds: 60
  # Resources limits and requests
  #
  # Check the following link for more details.
  #
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 650Mi
  # Fluent-bit pods additional labels
  #
  # Check the following link for more details about labels.
  #
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels:
    networking.resources.gardener.cloud/to-all-shoots-external-otelcol-collector-tcp-4317: "allowed"
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-runtime-apiserver: allowed
  # Fluent-bit pods additional annotations
  podAnnotations:
  # Fluent-bit pods tolerations for running on all nodes
  #
  # Check the following link for more details about annotations.
  #
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  # Fluent-bit pods priority class name
  priorityClassName: gardener-system-600
  # Fluent Bit Service settings.
  #
  # Check the following link for more details.
  #
  # https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    annotations:
      networking.resources.gardener.cloud/from-all-seed-scrape-targets-allowed-ports: '[{"port":2020,"protocol":"TCP"},{"port":2021,"protocol":"TCP"}]'
      networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"kubernetes.io/metadata.name":"garden"}}]'
      networking.resources.gardener.cloud/pod-label-selector-namespace-alias: "extensions"
  # Fluent Bit configuration  settings
  config:
    # Set the flush time in seconds.nanoseconds.
    flushSeconds: 30
    # Fluent Bit log level. Valid values are off, error, warn, info, debug, and trace
    logLevel: info
    # HTTP server for health checks and metrics.
    httpServer: true
    # Set listening interface for HTTP Server when it's enabled.
    httpListen:
    # Set TCP Port for the HTTP Server.
    httpPort: 2020
